// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://isjbdwxngfrgftfannzi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlzamJkd3huZ2ZyZ2Z0ZmFubnppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4ODI3MTYsImV4cCI6MjA2MTQ1ODcxNn0.21826sdn-w0kx6PIkZXbiWLZiqpT4-zuWS3y0zY09n4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);